
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAz
 */
public class mainForm extends javax.swing.JFrame {

    
    //Region critica
    String[] enemigos = new String[3]; //nombres de los enemigos a vencer
    String[] estado = new String[3]; // Estado de cada enemigo
    float[] dificultad = new float[3];
    int enemigos_vencidos = 0;
    
    /**
     * Creates new form mainForm
     */
    public mainForm() {
        initComponents();
        enemigos[0] = "Shang Tsung";
        estado[0] = "Waiting";
        dificultad[0] = 5;
        enemigos[1] = "Mptaro";
        estado[1] = "Waiting";
        dificultad[1] = 6;
        enemigos[2] = "Shao Kang";
        estado[2] = "Waiting";
        dificultad[2] = 7;
    }

    public class Peleador extends Thread{
        String nombre;
        int fuerza; // 1-10

        public Peleador(String nombre) {
            this.nombre = nombre;
        }
        
        @Override
        public void run(){
            //calcular fuerza
            this.fuerza = (int)((Math.random() * 10) + 1);
            System.out.println("Soy el peleador "+this.nombre+ " Y tengo una fuerza de "+this.fuerza);
            
            //Entrar a la torre
            if(estado[0].equals("Waiting")){
                estado[0] = "Fighting";
                lblEstado1.setText("Peleando com " + this.nombre);
                if(this.fuerza > dificultad[0]){
                    //Vencio al primer enemigo
                    estado[0] = "Defeated";
                    lblEstado1.setText("Derrotado por " + this.nombre);
                    //A pelear con el enemigo 2
                    estado[1] = "Fighting";
                    lblEstado2.setText("Peleando com " + this.nombre);
                    if(this.fuerza > dificultad[1]){
                        ////Vencio al segundo enemigo
                        estado[1] = "Defeated";
                        lblEstado2.setText("Derrotado por " + this.nombre);
                        //A pelear con el enemigo final
                        estado[2] = "Fighting";
                        lblEstado3.setText("Peleando com " + this.nombre);
                        if(this.fuerza > dificultad[2]){
                            //
                            estado[2] = "Defeated";
                            lblEstado3.setText("Derrotado por " + this.nombre);
                        }else{
                            reiniciarTorre();
                        }
                    }
                    else{
                        reiniciarTorre();
                    }
                }else{
                    reiniciarTorre();
                }
            }
            //finalizar participacion
            System.out.println(this.nombre + " Se despide");
        }
        
        public void reiniciarTorre(){
            estado[0] = "Waiting";
            lblEstado1.setText("Esperando...");
            estado[1] = "Waiting";
            lblEstado2.setText("Esperando...");
            estado[2] = "Waiting";
            lblEstado3.setText("Esperando...");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblEnemigo1 = new javax.swing.JLabel();
        lblEstado1 = new javax.swing.JLabel();
        lblEnemigo2 = new javax.swing.JLabel();
        lblEstado2 = new javax.swing.JLabel();
        lblEnemigo3 = new javax.swing.JLabel();
        lblEstado3 = new javax.swing.JLabel();
        BtnIniciar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Mortal Kombat");

        lblEnemigo1.setText("Shang Tsung");

        lblEstado1.setText("Esperando...");

        lblEnemigo2.setText("Motaro");

        lblEstado2.setText("Esperando...");

        lblEnemigo3.setText("Shao Khan");

        lblEstado3.setText("Esperando...");

        BtnIniciar.setText("Iniciar");
        BtnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIniciarActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblEnemigo2)
                        .addGap(66, 66, 66)
                        .addComponent(lblEstado2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnemigo3)
                                .addGap(66, 66, 66)
                                .addComponent(lblEstado3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEnemigo1)
                                .addGap(66, 66, 66)
                                .addComponent(lblEstado1)))))
                .addGap(92, 92, 92))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(156, 156, 156))))
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnemigo3)
                    .addComponent(lblEstado3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnemigo2)
                    .addComponent(lblEstado2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnemigo1)
                    .addComponent(lblEstado1))
                .addGap(38, 38, 38)
                .addComponent(BtnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIniciarActionPerformed
        // TODO add your handling code here:
        Peleador peleador1 = new Peleador("Sub-Zero");
        Peleador peleador2 = new Peleador("Scorpion");
        Peleador peleador3 = new Peleador("Raiden");
        peleador1.start();
        peleador2.start();
        peleador3.start();
    }//GEN-LAST:event_BtnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIniciar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEnemigo1;
    private javax.swing.JLabel lblEnemigo2;
    private javax.swing.JLabel lblEnemigo3;
    private javax.swing.JLabel lblEstado1;
    private javax.swing.JLabel lblEstado2;
    private javax.swing.JLabel lblEstado3;
    // End of variables declaration//GEN-END:variables
}
